name: Sync submodules
on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PUBTAGS_BOT_REPO_TOKEN }}
      - name: Update submodules
        run: |
          git submodule update --remote
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          push-to-fork: publisher-ads-audits-bot/google-publisher-tag-playground
          token: ${{ secrets.PUBTAGS_BOT_REPO_TOKEN }}
          title: "Update submodules"
          body: "Automated PR to update submodules of googleads/google-publisher-tag-playground"
          commit-message: "Update submodules"
          branch: "submodules"
          delete-branch: true
