name: Sync submodules
on:
  schedule:
    - cron: "*/30 * * * 1-5" # every 30 minutes, Mon - Fri
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PUBTAGS_BOT_REPO_TOKEN }}
      - name: Update submodules
        run: |
          git submodule update --remote
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          push-to-fork: publisher-ads-audits-bot/google-publisher-tag-playground
          token: ${{ secrets.PUBTAGS_BOT_REPO_TOKEN }}
          committer: Google Publisher Tags Bot <publisher-ads-audits-bot@google.com>
          title: "Update submodules"
          body: "Automated PR to update submodules of googleads/google-publisher-tag-playground"
          commit-message: "Update submodules"
          branch: "submodules"
          delete-branch: true
